@baseUrl = http://localhost:8080

# Проверка, что сервер жив
GET {{baseUrl}}/api/health


### 1) Без токена 
GET {{baseUrl}}/api/checks


### A) Register 
# @name regA
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "email": "a@example.com",
  "name": "User A",
  "password": "secret123"
}

### A) Login 
# @name loginA
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "a@example.com",
  "password": "secret123"
}


### A) Create check 
# @name chkA
POST {{baseUrl}}/api/checks
Content-Type: application/json
Authorization: Bearer {{loginA.response.body.token}}


{
  "label": "A check",
  "text": "Введение\nТеоретическая часть\nПрактическая часть\nМетодология\nРезультаты\nВыводы\nСписок литературы\nПриложения"
}

### A) Список своих проверок 
GET {{baseUrl}}/api/checks
Authorization: Bearer {{loginA.response.body.token}}



### B) Register 
# @name regB
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "email": "b@example.com",
  "name": "User B",
  "password": "secret123"
}

### B) Login 
# @name loginB
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "b@example.com",
  "password": "secret123"
}

### 2) B пытается получить check A 
GET {{baseUrl}}/api/checks/{{chkA.response.body.id}}
Authorization: Bearer {{loginB.response.body.token}}


### 3) Плохой токен 
GET {{baseUrl}}/api/checks
Authorization: Bearer BAD.TOKEN.VALUE
